apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-sqlite
  labels:
    app: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: <MLFLOW_S3_USER_ARN>
      labels:
        app: mlflow
    spec:
      volumes:
      - name: mlflow-pvc-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
      containers:
        - image: quay.io/numaio/mlflow
          name: mlflow
          args:
          - server
          - --default-artifact-root
          - s3://<MLFLOW_BUCKET>/
          - --serve-artifacts
          - --backend-store-uri
          - sqlite:///mlflow.db
          - --host
          - "0.0.0.0"
          - --port
          - "5000"
          command:
          - mlflow
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /app
              name: mlflow-pvc-storage
---
kind: Service
apiVersion: v1
metadata:
  name: mlflow-service
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000