apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-query-service-config
data:
  config.yaml: |
    general:
      channelCapacity: 
        capacity: 20
        dropDisabled: false       
      maxAge: 60
      leaderElectionEnabled: true
    prometheusJobs:
      - name: "query-1"
        queryConfig:
          interval: "30s"
          source: "http://thanos.addon-metricset-ns.svc:9090"
          query: "namespace_app_rollouts_http_request_error_rate"
          backoff:
            durationSeconds: 1
            factor: 2
            maxSteps: 5
        sendConfig:
          targets:
            - url: "https://numalogic-rollouts-pipeline-input-svc.ged-metrics-puller.svc:8443/vertices/input"
              insecure: true
          backoff:
            durationSeconds: 1
            factor: 2
            maxSteps: 5