apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-query-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-query-service
  template:
    metadata:
      labels:
        app: prometheus-query-service
    spec:
      containers:
        - name: metrics-query-service
          image: quay.io/numaio/numalogic-prometheus/prometheus-query-service:latest
          env:
            - name: CONFIG_PATH
              value: "/home/appuser/config/config.yaml"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: metrics-query-service-config
              mountPath: /home/appuser/config
      volumes:
        - name: metrics-query-service-config
          configMap:
            name: metrics-query-service-config
            optional: true