apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-query-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-query-service
  template:
    metadata:
      labels:
        app: metrics-query-service
    spec:
      serviceAccountName: metrics-query-service
      containers:
        - name: metrics-query-service
          image: docker.intuit.com/oss-analytics/metrics-query-service/service/metrics-query-service:0.2.14
          env:
            - name: CONFIG_PATH
              value: "/home/appuser/config/config.yaml"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: metrics-query-service-config
              mountPath: /home/appuser/config
      volumes:
        - name: metrics-query-service-config
          configMap:
            name: metrics-query-service-config
            optional: true