apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-query-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-query-service-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-query-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-query-service-role
subjects:
- kind: ServiceAccount
  name: metrics-query-service
---
apiVersion: v1
data:
  config.yaml: "general:\n  channelCapacity: \n    capacity: 20\n    dropDisabled:
    false       \n  maxAge: 60\n  leaderElectionEnabled: true\nprometheusJobs:\n  -
    name: \"query-1\"\n    queryConfig:\n      interval: \"30s\"\n      source: \"http://thanos.addon-metricset-ns.svc:9090\"\n
    \     query: \"namespace_app_rollouts_http_request_error_rate\"\n      backoff:\n
    \       durationSeconds: 1\n        factor: 2\n        maxSteps: 5\n    sendConfig:\n
    \     targets:\n        - url: \"https://numalogic-rollouts-pipeline-input-svc.ged-metrics-puller.svc:8443/vertices/input\"\n
    \         insecure: true\n      backoff:\n        durationSeconds: 1\n        factor:
    2\n        maxSteps: 5"
kind: ConfigMap
metadata:
  name: prometheus-query-service-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-query-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-query-service
  template:
    metadata:
      labels:
        app: prometheus-query-service
    spec:
      containers:
      - env:
        - name: CONFIG_PATH
          value: /home/appuser/config/config.yaml
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/numaio/numalogic-prometheus/prometheus-query-service:latest
        name: prometheus-query-service
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /home/appuser/config
          name: prometheus-query-service-config
      serviceAccountName: metrics-query-service
      volumes:
      - configMap:
          name: prometheus-query-service-config
          optional: true
        name: prometheus-query-service-config
