apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-query-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-query-service-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-query-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-query-service-role
subjects:
  - kind: ServiceAccount
    name: metrics-query-service
