apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: numaflow-system
resources:
  - namespace.yaml
  - https://github.intuit.com/oss-analytics/numaproj/numaflow-versions/v0.7.2?ref=main