apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: numaflow-system
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/numaproj/numaflow/v0.6.4/config/install.yaml
