apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - ./kube-state-metrics
  - clusterRole.yaml
  - prometheus-deployment.yaml
  - prometheus-server-conf.yaml
  - prometheus-service.yaml
  - pushgateway.yaml
