---
# Source: redis-cluster/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: numalogic-redis-cluster-headless
  labels:
    app.kubernetes.io/name: redis-cluster
    helm.sh/chart: redis-cluster-8.3.1
    app.kubernetes.io/instance: bitnami
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
    - name: tcp-redis-bus
      port: 16379
      targetPort: tcp-redis-bus
  selector:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: bitnami
