---
# Source: redis-cluster/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: numalogic-redis-cluster
  labels:
    app.kubernetes.io/name: redis-cluster
    helm.sh/chart: redis-cluster-8.3.1
    app.kubernetes.io/instance: bitnami
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "NXJtbWZYdHNiTA=="
