name: Build Release CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Set output
      id: vars
      run: |
        echo "version=$(poetry version -s)" >> $GITHUB_ENV

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_PASSWORD }}

    - name: Docker Build
      env:
        QUAYIO_ORG: quay.io/numaio
        PLATFORM: linux/x86_64
        TARGET: numalogic-prometheus/udf
      run: |
        branch=$(basename $GITHUB_REF)
        
        tag=${{ env.version }}
        if [ $branch != "main" ]; then
          tag="${branch}v${tag}"
        fi
        
        image_name="${QUAYIO_ORG}/numalogic-prometheus/udf:${tag}"
        
        docker buildx build \
          --output "type=image,push=true" \
          --platform="${PLATFORM}" \
          --tag $image_name .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          # ${{ steps.vars.outputs.tag }} has been released. 
          [quay.io/numaio/numalogic-prometheus/udf:${{ steps.vars.outputs.tag }}](https://quay.io/repository/numaio/numalogic-prometheus/udf)
        draft: false
        prerelease: false
