name: Build Release CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_PASSWORD }}

    - name: Install poetry
      run: pipx install poetry

    - name: Docker Build
      env:
        QUAYIO_ORG: quay.io/numaio
        PLATFORM: linux/x86_64
        TARGET: numalogic-prometheus/udf
      run: |
        tag= ${poetry version -s}
#        if [ $tag = "main" ]; then
#          tag="latest"
#        fi
        
        image_name="${QUAYIO_ORG}/numalogic-prometheus/udf:${tag}"
        
        docker buildx build \
          --output "type=image,push=true" \
          --platform="${PLATFORM}" \
          --tag $image_name .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          # ${{ steps.vars.outputs.tag }} has been released. 
          [quay.io/numaio/numalogic-prometheus/udf:${{ steps.vars.outputs.tag }}](https://quay.io/repository/numaio/numalogic-prometheus/udf)
        draft: false
        prerelease: false
