name: PyPi Publish

on:
  pull_request:
    branches: [ "metrics" ]
jobs:
  pypi_publish:
    if: github.repository == 'numaproj/numalogic-prometheus'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    name: Publish to PyPi
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install --all-extras

      - name: Build dist
        run: poetry build

      - name: Publish
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
